PoS/urls.py
from django.urls import re_path
from .views import *




urlpatterns =[
    re_path(r'^$',view=homepage),
    re_path(r'νέα-παραγγελία/(?P<dk>\d+)/$',view=new_order),
    re_path(r'επέλεξε-συνταγή/(?P<dk>\d+)/$',view=add_products_to_order_main),
    re_path(r'επέλεξε-συνταγή/(?P<dk>\d+)/κατηγορία/(?P<ck>\d+)$',view=add_products_to_order_category),
    re_path(r'επέλεξε-συνταγή/προσθήκη-συνταγής/(?P<dk>\d+)/(?P<ck>\d+)/(?P<pk>\d+)',view=add_recipe_to_order_from_cat),

    re_path(r'επέλεξε-συνταγή/(?P<dk>\d+)/πληρωμή$',view=order_pay_not_complete),






    re_path(r'επέλεξε-συνταγή/προσθήκη-συνταγής/(?P<dk>\d+)/(?P<pk>\d+)',view=add_recipe_to_order),
    re_path(r'επέλεξε-συνταγή/διαγραφή/(?P<dk>\d+)/(?P<pk>\d+)',view=delete_recipe_from_order),
    re_path(r'επέλεξε-συνταγή/edit/(?P<dk>\d+)/(?P<pk>\d+)',view=edit_recipe_from_order),
    re_path(r'πληρωμή/(?P<dk>\d+)/$',view=order_paid),
    re_path(r'εκτύπωση/$',view=print_order_to_kitchen),



    re_path(r'lianiki/$', view=lianiki_section),
    re_path(r'lianiki/create-return/$', view=create_return_order),
    re_path(r'return-products/(?P<dk>\d+)/$', view= return_products),


    re_path(r'lianiki/new-order/$', view=new_lianiki_order),
    re_path(r'lianiki/order/(?P<dk>\d+)/$', view=lianiki_show_categories),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/$', view=lianiki_choose_category),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/add/$', view=lianiki_add_product),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/(?P<sk>\d+)/$', view=lianiki_add_product_with_color),
    re_path(r'lianiki/order/only_color/(?P<dk>\d+)/(?P<pk>\d+)/(?P<sk>\d+)/$', view=lianiki_add_product_with_only_color),


    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/edit/$', view=lianiki_edit_order_item),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/delete/$', view=lianiki_delete_order_item),
    re_path(r'lianiki/order/(?P<dk>\d+)/pay/$', view=lianiki_order_pay_not_complete),
    re_path(r'lianiki/order/(?P<dk>\d+)/closed/$', view=lianiki_order_closed),




    re_path(r'παραγγελίες/$',view=active_orders),
    re_path(r'stats/$',view=total_stats),
    re_path(r'admin/$',view=admin_section),
    re_path(r'admin/deactive-day/$', view=admin_section_deactive_day),
    re_path(r'admin/active-day/$',view= admin_section_create_new_day),

    re_path(r'admin/deactive-month/$', view=admin_section_deactive_month),
    re_path(r'admin/active-month/$',view= admin_section_create_new_month),

    re_path(r'admin/deactive-year/$', view=admin_section_deactive_year),
    re_path(r'admin/active-year/$',view= admin_section_create_new_year),



    ]

eshop_grigoris/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from tools.views import set_up_database
from django.conf import settings
from django.contrib.auth import logout

from products.views import *
from esoda_katastimata.views import homepage as katastimata_homepage
from mysite.views import homepage as mysite_homepage

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    path('', welcome_page, name='welcome_page'),
    re_path(r'^accounts/',include('account.urls')),
    re_path(r'^αποθήκη/',include('products.urls')),
    re_path(r'^πληρωμές-εισπράξεις/',include('transcations.urls')),
    re_path(r'^συνταγές/',include('recipes.urls')),
    re_path(r'^PoS/',include('PoS.urls')),
    re_path(r'^reports/',include('reports.urls')),
	re_path(r'^katastimata/',include('esoda_katastimata.urls')),
    re_path(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    # that url setup the database, comment it after the use
    #url(r'^database/',view=set_up_database),





    re_path(r'^inventory/', include('inventory_manager.urls')),
    
    
    re_path(r'^site/$', mysite_homepage,),
    re_path(r'^katastimata/$', katastimata_homepage,),
    re_path(r'^homepage/$', homepage,),
    re_path(r'^homepage/new_all/last_order/$', add_product_to_order,name='last_one'),
    re_path(r'^homepage/new_all/last_order/(?P<dk>\d+)/$',order_done,),
    re_path(r'^homepage/new_all/last_order/edit/(?P<dk>\d+)/$', done_order_edit_id,),
    re_path(r'^homepage/new_all/last_order/product/edit/(?P<dk>\d+)/$', done_order_product_id,),
    re_path(r'^homepage/new_all/last_order/product/add/(?P<dk>\d+)/$', done_order_add_product,),
    re_path(r'^homepage/new_all/last_order/product/delete/(?P<dk>\d+)/$', done_order_delete_id,),



    re_path(r'^homepage/edit_all/$', edit_all,),
    re_path(r'^homepage/edit_all/orders/$', edit_orders_section,),
    re_path(r'^homepage/edit_all/order/(?P<dk>\d+)/$', edit_order,),
    re_path(r'^homepage/edit_all/order_id/(?P<dk>\d+)/$', edit_order_id,),
    re_path(r'^homepage/edit_all/order_id/delete/(?P<dk>\d+)/$', delete_order_id,),
    re_path(r'^homepage/edit_all/orders/add/(?P<dk>\d+)/$', add_order_id,),



    re_path(r'^homepage/edit_all/products/(?P<dk>\d+)/$',edit_product_id,),
    re_path(r'^homepage/edit_all/products/$', products_edit_section,),
    re_path(r'^homepage/edit_all/products/vendor/(?P<dk>\d+)/$',edit_product_vendor_id),

    re_path(r'^homepage/edit_all/vendors/$', edit_vendor_section,),
    re_path(r'^homepage/edit_all/vendors/(?P<dk>\d+)/$', edit_vendor_id,),


    re_path(r'^inventory_informations/$', informations_inventory,),
    re_path(r'^inventory_informations/προμηθευτές/$', info_vendors_section,),
    re_path(r'^inventory_informations/προμηθευτές-ανάλυση/$', info_vendor_personal_stuff,),
    re_path(r'^inventory_informations/προμηθευτές-υπόλοιπο/$', info_vendor_ipoloipo,),
    re_path(r'^inventory_informations/προμηθευτές-υπόλοιπο/(?P<dk>\d+)/$', info_vendor_ipoloipo_id,),
    re_path(r'^inventory_informations/προμηθευτές-ανά-προμηθευτή/$', info_vendor_order,),
    re_path(r'^inventory_informations/προμηθευτές-ανά-προμηθευτή/(?P<dk>\d+)/$', info_vendor_order_id,),




    re_path(r'^inventory_informations/calendar/$', inventory_info_calendar,),
    re_path(r'^inventory_informations/order/$', info_order,),
    re_path(r'^inventory_informations/πληρωμές/$', info_calendar_payments,),


    re_path(r'^inventory_informations/προιόντα/$', info_products,),



    re_path(r'^inventory_informations/κατηγορία/', info_products_category,),
    re_path(r'^inventory_informations/προμηθευτής/', info_products_vendors,),
    re_path(r'^inventory_informations/χονδρική/', info_products_xondriki,),
    re_path(r'^inventory_informations/προιόντα/(?P<dk>\d+)$', info_products_id,),







 




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esoda_katastimata/urls.py
from django.urls import re_path
from .views import *




urlpatterns =[
    re_path(r'^$',view=homepage),
    re_path(r'active-month/$',view=create_new_month),
    re_path(r'deactive-month/$',view=deactive_month),
    re_path(r'active-year/$',view=create_new_year),
    re_path(r'deactive-year/$',view=deactive_year),
    re_path(r'new-esoda/$',view=new_esoda),
    re_path(r'esodo/(?P<dk>\d+)/$',view=edit_day),

    re_path(r'income/year/(?P<yk>\d+)/$',view=esoda_income_choose_year),
    re_path(r'income/month/(?P<mk>\d+)/$',view=esoda_income_choose_month),



    ]

PoS/models.py
from turtle import onclick
from django.db import models
from recipes.models import *
from django.utils import timezone

# Create your models here.


class YearlyIncomeGreg(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(default=str(datetime.datetime.today().year), unique=True, max_length=64)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_profit_per_order(self):
        if self.order_number ==0:
            return 0
        else:
            return self.show_profit()/self.order_number

    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number




class UserInputIncomeSeason(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(max_length=64)
    date = models.DateField(default=timezone.now)
    date_done = models.DateField(default=timezone.now)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number






class MonthlyIncomeGreG(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(default=str(datetime.datetime.now().strftime("%B")),max_length=64)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)
    year = models.ForeignKey(YearlyIncomeGreg,null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_profit_per_order(self):
        if self.order_number ==0:
            return 0
        else:
            return self.show_profit()/self.order_number





    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number




class DailyIncomeGreG(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(default=str(datetime.datetime.today().date()),unique=True, max_length=64)
    date = models.DateField(default=timezone.now)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)
    month = models.ForeignKey(MonthlyIncomeGreG,null=True, on_delete=models.CASCADE)
    year = models.ForeignKey(YearlyIncomeGreg,null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_profit_per_order(self):
        if self.order_number ==0:
            return 0
        else:
            return self.show_profit()/self.order_number



    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number










class Table(models.Model):
    STATUS_ =(('a','Διαθέσιμο'),('b','Παραγγελία σε εξέλιξη'),('c','Απενεργοποιημένπ'))
    title = models.CharField(max_length=10, unique=True, )
    status = models.CharField(max_length=1, choices=STATUS_, default='a')

    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name="Τραπέζια"



class RestoOrder(models.Model):
    STATUS_CHOICES =(('a','Σε εξέλιξη'),('b','Αποπληρώθηκε'),('c','Ακύρωση'))
    title = models.CharField(max_length=50,default=timezone.now)
    notes = models.TextField(null=True,blank=True)
    table = models.ForeignKey(Table,verbose_name='Τραπέζι', on_delete=models.CASCADE)
    day_added = models.DateTimeField(default=timezone.now)
    discount = models.IntegerField(default=0, verbose_name='Έκπτωση',)

    value = models.DecimalField(max_digits=6,decimal_places=2,default=0,verbose_name='Αξία Παραγγελίας')
    total_cost  = models.DecimalField(max_digits=6,decimal_places=2,default=0,verbose_name='Συνολικό Κόστος Παραγγελίας')
    paid_value = models.DecimalField(max_digits=6,decimal_places=2,default=0,verbose_name='Αποπληρωμένο Πόσο')
    status = models.CharField(max_length=1,choices=STATUS_CHOICES, default='a')




    year = models.ForeignKey(YearlyIncomeGreg, null=True, blank=True, on_delete=models.CASCADE)
    month =models.ForeignKey(MonthlyIncomeGreG,null=True, blank=True, on_delete=models.CASCADE)
    day = models.ForeignKey(DailyIncomeGreG,null=True,blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name="Παραγγελία Εστιατορίου"
        
        
        
    def remaining_value(self):
        return str(self.value - self.paid_value)

    def __str__(self):
        return self.title

    def order_table_closed(self,dk):
        # gets the order
        order = RestoOrder.objects.get(id= dk)


        #updates the daily ,monthly,yearly incomes and costs
        order.day.money_income += order.paid_value
        order.day.money_outcome +=order.total_cost
        order.day.save()

        order.month.money_income += order.paid_value
        order.month.money_outcome += order.total_cost
        order.month.order_number +=1
        order.month.save()

        order.year.money_income += order.paid_value
        order.year.money_outcome += order.total_cost
        order.year.order_number +=1
        order.year.save()
        #---------------------------------

        #get the order products
        order_items = order.restoorderitem_set.all()
        for ele in order_items:
            # order quantity per item
            quantity = ele.qty
            # updates the Recipes categories cost and income
            ele.title.category.day_cost += ele.title.recipe_cost*ele.qty
            ele.title.category.month_cost += ele.title.recipe_cost*ele.qty
            ele.title.category.yearly_cost += ele.title.recipe_cost*ele.qty
            #ele.title.category.costum_cost_cost += ele.title.recipe_cost

            ele.title.category.day_income += ele.title.recipe_price*ele.qty
            ele.title.category.month_income += ele.title.recipe_price*ele.qty
            ele.title.category.yearly_income += ele.title.recipe_price*ele.qty
            #ele.title.category.costum_income += ele.title.recipe_price
            ele.title.category.save()

            #gets th products for every recipe
            recipe_item = ele.title.recipeitem_set.all()
            #updates the warehouse stock for very product used on Recipes
            for ele in recipe_item:
                qty_kila = ele.product.qty_kilo
                posotita = ele.qty
                ele.product.reserve -= (quantity*posotita)/qty_kila
                ele.product.save()

        order.status='b'
        order.save()






class RestoOrderItem(models.Model):
    title = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    order = models.ForeignKey(RestoOrder, on_delete=models.CASCADE)
    cost =  models.DecimalField(max_digits=6,decimal_places=2,default=0)
    price = models.DecimalField(max_digits=6,decimal_places=2,default=0)
    qty= models.DecimalField(max_digits=3,decimal_places=1,default=1, verbose_name='Ποσότητα')

    class Meta:

esoda_katastimata/templates/pos/add_product_category.html
{% extends 'PoS/add_products_main.html' %}


{% block center %}
    <div class="ui segments">
        <div class="ui inverted blue segment">
            <h2 style="text-align: center">{{ categories.title }}</h2>
        </div>
        <div class="ui segments">
            <div class="ui segment">

                <a href="/PoS/επέλεξε-συνταγή/{{ order.id }}" class="ui massive green button"><i class="huge browser icon"></i><br>Επιστροφή</a>

            </div>

            <div class="ui divider segment">Ολα τα Προιόντα</div>
            <div class="ui segment">
                {% for ele in recipes %}
                    <a href="/PoS/επέλεξε-συνταγή/προσθήκη-συνταγής/{{ order.id }}/{{ categories.id }}/{{ ele.id }}" class="ui massive blue button"><i class="share square icon"></i>{{ ele.title }}</a>
                {% endfor %}

            </div>
        </div>
    </div>


{% endblock %}

esoda_katastimata/templates/pos/add_product_to_order.html
{% extends 'PoS/add_products_main.html' %}


{% block center %}

    <div class="ui segments">
        <div class="ui inverted blue segment">
            <h2 style="text-align: center">Επέλεξε συνταγή για το τραπέζι {{ order.table.title }}</h2>
        </div>
        <div class="ui segments">
            <div class="ui segment">

                <a href="/PoS/επέλεξε-συνταγή/{{ order.id }}" class="ui massive green button"><i class="huge browser icon"></i><br>Επιστροφή</a>

            </div>

            <div class="ui divider segment">Επιλογή Ποσότητας</div>
            <div class="ui segment">
                <div class="ui form">

                <form class="ui form" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                    {{ form }}
                    <input style="width: 100%" type="submit" name="submit" class="ui green button segment" value="Προσθήκη"/>
                </form>
            </div>

            </div>
        </div>
    </div>


{% endblock %}


{% block right_side %}
    <div class="ui segments">
        <div style="text-align: center" class="ui inverted red segment">
            Όδηγίες!
        </div>
        <div class="ui segment">
            <h1>ΠΕΙΡΑΖΕΙΣ ΜΟΝΟ την Τιμή εαν θες να κάνεις έκπτωση, και την Ποσότητα ανάλογα την παραγγελία</h1>
        </div>
    </div>
     <div class="ui segments">
        <div style="text-align: center" class="ui inverted blue segment">
            Οδηγίες Παρασκευής
        </div>
        <div class="ui horizontal  segments">
            <table class="ui table segment">
                <thead>
                    <tr>
                        <th>Συστατικά</th>
                    </tr>

                </thead>
                    {% for ele in recipe.recipeitem_set.all %}
                    <tr>
                        <td>{{ ele.recipe_part }}</td>
                    </tr>
                {% endfor %}

            </table>
            <div class="ui text-info segment">
                {{ recipe.description }}
            </div>

        </div>
    </div>


{% endblock %}

esoda_katastimata/templates/pos/admin_section.html
{% extends 'PoS/homepage.html' %}



{% block center %}

    <div class="ui segments">
        <div style="text-align: center" class="ui blue  header inverted segment">Πληροφορίες</div>
        <div class="ui horizontal segments">
            <div class="ui statistic segment">
                 <div class="value">
                      <i class=" green calendar outline icon"></i> {{ day }}
                 </div>
                <div class="label">
                      Ημερομηνία
                </div>
            </div>
            <div class="ui tiny statistic segment">
                 <div class="value">
                      <i class="  green calendar outline icon"></i> {{ month }}
                 </div>
                <div class="label">
                    Τρέχων Μήνας
                </div>
            </div>
            <div class="ui tiny statistic segment">
                 <div class="value">
                      <i class="  green calendar outline icon"></i> {{ year }}
                 </div>
                <div class="label">
                    Τρέχων Χρονιά
                </div>
            </div>
        </div>
        <div class="ui divider segment"></div>
        {% if day.status == 'a' %}
            <div style="width: 100%" class="ui red inverted button segment">
                <a href="/PoS/admin/deactive-day/">Κλείσιμο Ημέρας</a>
            </div>
            {% else %}
            <div  style="width: 100%" class="ui green inverted button segment">
                <a href="/PoS/admin/active-day/"> Άνοιγμα νέας ημέρας</a>
            </div>
            {% endif  %}
        <div class="ui divider segment"></div>
        <div class="ui inverted blue header segment">
            Τραπέζια
        </div>
        <table class="ui blue table segment">
            <thead>
                <tr>
                    <th>Όνομα Τραπεζιού</th>
                    <th>Κατάσταση</th>
                </tr>
            </thead>
            <tbody>
                {% for ele in tables %}
                    <tr>
                        <td>{{ ele.title }}</td>
                        {% if ele.status == 'a' %}
                        <td style="background-color: #448012">{{ ele.get_status_display }}</td>
                        {% elif ele.status == 'b' %}
                        <td style="background-color: #29a5ff">{{ ele.get_status_display }}</td>
                        {% else %}
                        <td style="background-color: #ff814e">{{ ele.get_status_display }}</td>
                        {% endif%}
                    </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td  class="ui  button"><a href="/admin/PoS/table/">Επεξεργασία Τραπεζιών</a></td>
                </tr>
            </tbody>

        </table>


       </div>
    


{% endblock %}

{% block right_side %}

    <div class="ui segments">
        <div class="ui red inverted header segment">Προσοχή κλείσιμο ΜΟΝΟ στις αλλαγές κάθε Μήνα ή Χρονιάς</div>
        <div class="ui divider segmnent"></div>
        <div class="ui segments">
            {% if month.status == 'a' %}
            <div class="ui red inverted button segment">
                <a href="/PoS/admin/deactive-month/"> Κλείσιμο Μήνα</a>
            </div>
            {% else %}
            <div class="ui green inverted button segment">
               <a href="/PoS/admin/active-month/">Άνοιγμα Νέου Μήνα</a>
            </div>
            {% endif  %}

            {% if year.status == 'a' %}
            <div style="margin-left: 30%" class="ui red inverted button segment">
                 <a href="/PoS/admin/deactive-year/">Κλείσιμο Χρονιάς</a>
            </div>
            {% else %}
            <div style="margin-left: 30%" class="ui green inverted button segment">
                 <a href="/PoS/admin/active-year/">Άνοιγμα Νέας Χρονιάς</a>
            </div>
            {% endif  %}
        </div>

{% endblock %}

esoda_katastimata/templates/pos/admin_section_create_day.html
{% extends 'PoS/homepage.html' %}


{% block center %}
    <style>
        #id_month,#id_year {
            display:none;
        } 
        label[for=id_month],label[for=id_year]{
            display:none;
            }    
    
    
    </style>

    <div class="ui segments">
        <div class="ui segment header inverted blue">Δημιουργία Ήμέρας</div>
        <form class="ui form segment" enctype="multipart/form-data" method="post">{% csrf_token %}
            {{ form }}
            <input style="margin-left: 70%" type="submit" name="submit" class="ui  green button" value="Δημιουργία "/>
        </form>
    </div>
{% endblock %}

esoda_katastimata/templates/pos/homepage.html
<!DOCTYPE html>
<html lang="el">

<head lang="el">
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>PoS</title>
    <link rel="stylesheet" href="{% static 'Semantic-UI-CSS-master/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'my_static/index.css' %}">


</head>
<body>

    <div class="ui grid">

        <div class="three wide column">
            {% block left_side %}
                <div class="ui inverted black segments">
                    <div class="ui inverted header segment">
                        <h1>PoS</h1>
                    </div>
                    <div class="ui divider segment"></div>


                    <div class="ui inverted black segment">
                        <a style="width: 100%" href="/PoS/lianiki/" class="ui massive green button">Λιανική</a>
                    </div>
                    <div class="ui inverted black segment">
                        <a style="width: 100%" href="/PoS/lianiki/" class="ui massive green button">Χονδρική</a>
                    </div>

                    <div class="ui inverted black segment">
                        <a style="width: 100%" href="/PoS/stats/" class="ui massive green button">Στατιστικά Ημέρας</a>
                    </div>

                    <div class="ui inverted black segment">
                        <a style="width: 100%" href="/PoS/admin/" class="ui massive green button">Admin Settings</a>
                    </div>
                    <div class="ui divider segment"></div>
                </div>


            {% endblock %}
        </div>
        <div class="eight wide column">
            {% block center %}
                <div class="ui segments">
                    <div class="ui inverted blue segment">
                        <h2 style="text-align: center">Tables</h2>
                    </div>
                    <div class="ui inverted segment">


                        {% for ele in table %}
                            <a href="/PoS/νέα-παραγγελία/{{ ele.id }}/" id="table_pos" style="text-align:center; width: 30%; height: 200px; margin-top: 2%" class="ui massive green button ">{{ ele.title }}</a>
                        {% endfor %}
                    </div>
                </div>

            {% endblock %}
        </div>
        <div class="five wide column">
            {% block right_side %}

            {% endblock %}
        </div>

    </div>











<script type="text/javascript" src="{% static 'jquery-1.12.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Semantic-UI-CSS-master/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'my_static/index.js' %}"></script>
</body>


</html>