PoS/urls.py
from django.urls import re_path
from .views import *




urlpatterns =[
    re_path(r'^$',view=homepage),
    re_path(r'νέα-παραγγελία/(?P<dk>\d+)/$',view=new_order),
    re_path(r'επέλεξε-συνταγή/(?P<dk>\d+)/$',view=add_products_to_order_main),
    re_path(r'επέλεξε-συνταγή/(?P<dk>\d+)/κατηγορία/(?P<ck>\d+)$',view=add_products_to_order_category),
    re_path(r'επέλεξε-συνταγή/προσθήκη-συνταγής/(?P<dk>\d+)/(?P<ck>\d+)/(?P<pk>\d+)',view=add_recipe_to_order_from_cat),

    re_path(r'επέλεξε-συνταγή/(?P<dk>\d+)/πληρωμή$',view=order_pay_not_complete),






    re_path(r'επέλεξε-συνταγή/προσθήκη-συνταγής/(?P<dk>\d+)/(?P<pk>\d+)',view=add_recipe_to_order),
    re_path(r'επέλεξε-συνταγή/διαγραφή/(?P<dk>\d+)/(?P<pk>\d+)',view=delete_recipe_from_order),
    re_path(r'επέλεξε-συνταγή/edit/(?P<dk>\d+)/(?P<pk>\d+)',view=edit_recipe_from_order),
    re_path(r'πληρωμή/(?P<dk>\d+)/$',view=order_paid),
    re_path(r'εκτύπωση/$',view=print_order_to_kitchen),



    re_path(r'lianiki/$', view=lianiki_section),
    re_path(r'lianiki/create-return/$', view=create_return_order),
    re_path(r'return-products/(?P<dk>\d+)/$', view= return_products),


    re_path(r'lianiki/new-order/$', view=new_lianiki_order),
    re_path(r'lianiki/order/(?P<dk>\d+)/$', view=lianiki_show_categories),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/$', view=lianiki_choose_category),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/add/$', view=lianiki_add_product),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/(?P<sk>\d+)/$', view=lianiki_add_product_with_color),
    re_path(r'lianiki/order/only_color/(?P<dk>\d+)/(?P<pk>\d+)/(?P<sk>\d+)/$', view=lianiki_add_product_with_only_color),


    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/edit/$', view=lianiki_edit_order_item),
    re_path(r'lianiki/order/(?P<dk>\d+)/(?P<pk>\d+)/delete/$', view=lianiki_delete_order_item),
    re_path(r'lianiki/order/(?P<dk>\d+)/pay/$', view=lianiki_order_pay_not_complete),
    re_path(r'lianiki/order/(?P<dk>\d+)/closed/$', view=lianiki_order_closed),




    re_path(r'παραγγελίες/$',view=active_orders),
    re_path(r'stats/$',view=total_stats),
    re_path(r'admin/$',view=admin_section),
    re_path(r'admin/deactive-day/$', view=admin_section_deactive_day),
    re_path(r'admin/active-day/$',view= admin_section_create_new_day),

    re_path(r'admin/deactive-month/$', view=admin_section_deactive_month),
    re_path(r'admin/active-month/$',view= admin_section_create_new_month),

    re_path(r'admin/deactive-year/$', view=admin_section_deactive_year),
    re_path(r'admin/active-year/$',view= admin_section_create_new_year),



    ]

eshop_grigoris/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from tools.views import set_up_database
from django.conf import settings
from django.contrib.auth import logout

from products.views import *
from esoda_katastimata.views import homepage as katastimata_homepage
from mysite.views import homepage as mysite_homepage

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    path('', welcome_page, name='welcome_page'),
    re_path(r'^accounts/',include('account.urls')),
    re_path(r'^αποθήκη/',include('products.urls')),
    re_path(r'^πληρωμές-εισπράξεις/',include('transcations.urls')),
    re_path(r'^συνταγές/',include('recipes.urls')),
    re_path(r'^PoS/',include('PoS.urls')),
    re_path(r'^reports/',include('reports.urls')),
	re_path(r'^katastimata/',include('esoda_katastimata.urls')),
    re_path(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    # that url setup the database, comment it after the use
    #url(r'^database/',view=set_up_database),





    re_path(r'^inventory/', include('inventory_manager.urls')),
    
    
    re_path(r'^site/$', mysite_homepage,),
    re_path(r'^katastimata/$', katastimata_homepage,),
    re_path(r'^homepage/$', homepage,),
    re_path(r'^homepage/new_all/last_order/$', add_product_to_order,name='last_one'),
    re_path(r'^homepage/new_all/last_order/(?P<dk>\d+)/$',order_done,),
    re_path(r'^homepage/new_all/last_order/edit/(?P<dk>\d+)/$', done_order_edit_id,),
    re_path(r'^homepage/new_all/last_order/product/edit/(?P<dk>\d+)/$', done_order_product_id,),
    re_path(r'^homepage/new_all/last_order/product/add/(?P<dk>\d+)/$', done_order_add_product,),
    re_path(r'^homepage/new_all/last_order/product/delete/(?P<dk>\d+)/$', done_order_delete_id,),



    re_path(r'^homepage/edit_all/$', edit_all,),
    re_path(r'^homepage/edit_all/orders/$', edit_orders_section,),
    re_path(r'^homepage/edit_all/order/(?P<dk>\d+)/$', edit_order,),
    re_path(r'^homepage/edit_all/order_id/(?P<dk>\d+)/$', edit_order_id,),
    re_path(r'^homepage/edit_all/order_id/delete/(?P<dk>\d+)/$', delete_order_id,),
    re_path(r'^homepage/edit_all/orders/add/(?P<dk>\d+)/$', add_order_id,),



    re_path(r'^homepage/edit_all/products/(?P<dk>\d+)/$',edit_product_id,),
    re_path(r'^homepage/edit_all/products/$', products_edit_section,),
    re_path(r'^homepage/edit_all/products/vendor/(?P<dk>\d+)/$',edit_product_vendor_id),

    re_path(r'^homepage/edit_all/vendors/$', edit_vendor_section,),
    re_path(r'^homepage/edit_all/vendors/(?P<dk>\d+)/$', edit_vendor_id,),


    re_path(r'^inventory_informations/$', informations_inventory,),
    re_path(r'^inventory_informations/προμηθευτές/$', info_vendors_section,),
    re_path(r'^inventory_informations/προμηθευτές-ανάλυση/$', info_vendor_personal_stuff,),
    re_path(r'^inventory_informations/προμηθευτές-υπόλοιπο/$', info_vendor_ipoloipo,),
    re_path(r'^inventory_informations/προμηθευτές-υπόλοιπο/(?P<dk>\d+)/$', info_vendor_ipoloipo_id,),
    re_path(r'^inventory_informations/προμηθευτές-ανά-προμηθευτή/$', info_vendor_order,),
    re_path(r'^inventory_informations/προμηθευτές-ανά-προμηθευτή/(?P<dk>\d+)/$', info_vendor_order_id,),




    re_path(r'^inventory_informations/calendar/$', inventory_info_calendar,),
    re_path(r'^inventory_informations/order/$', info_order,),
    re_path(r'^inventory_informations/πληρωμές/$', info_calendar_payments,),


    re_path(r'^inventory_informations/προιόντα/$', info_products,),



    re_path(r'^inventory_informations/κατηγορία/', info_products_category,),
    re_path(r'^inventory_informations/προμηθευτής/', info_products_vendors,),
    re_path(r'^inventory_informations/χονδρική/', info_products_xondriki,),
    re_path(r'^inventory_informations/προιόντα/(?P<dk>\d+)$', info_products_id,),







 




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esoda_katastimata/urls.py
from django.urls import re_path
from .views import *




urlpatterns =[
    re_path(r'^$',view=homepage),
    re_path(r'active-month/$',view=create_new_month),
    re_path(r'deactive-month/$',view=deactive_month),
    re_path(r'active-year/$',view=create_new_year),
    re_path(r'deactive-year/$',view=deactive_year),
    re_path(r'new-esoda/$',view=new_esoda),
    re_path(r'esodo/(?P<dk>\d+)/$',view=edit_day),

    re_path(r'income/year/(?P<yk>\d+)/$',view=esoda_income_choose_year),
    re_path(r'income/month/(?P<mk>\d+)/$',view=esoda_income_choose_month),



    ]

PoS/models.py
from turtle import onclick
from django.db import models
from recipes.models import *
from django.utils import timezone

# Create your models here.


class YearlyIncomeGreg(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(default=str(datetime.datetime.today().year), unique=True, max_length=64)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_profit_per_order(self):
        if self.order_number ==0:
            return 0
        else:
            return self.show_profit()/self.order_number

    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number




class UserInputIncomeSeason(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(max_length=64)
    date = models.DateField(default=timezone.now)
    date_done = models.DateField(default=timezone.now)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number






class MonthlyIncomeGreG(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(default=str(datetime.datetime.now().strftime("%B")),max_length=64)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)
    year = models.ForeignKey(YearlyIncomeGreg,null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_profit_per_order(self):
        if self.order_number ==0:
            return 0
        else:
            return self.show_profit()/self.order_number





    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number




class DailyIncomeGreG(models.Model):
    CHOICES = (('a','Σε εξέλιξη'),('b','Εκλεισε'))
    title = models.CharField(default=str(datetime.datetime.today().date()),unique=True, max_length=64)
    date = models.DateField(default=timezone.now)
    money_income = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    money_outcome = models.DecimalField(default=0, max_digits=8,decimal_places=2)
    order_number = models.IntegerField(default=0)
    status = models.CharField(max_length=1, default='a',choices=CHOICES)
    month = models.ForeignKey(MonthlyIncomeGreG,null=True, on_delete=models.CASCADE)
    year = models.ForeignKey(YearlyIncomeGreg,null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def show_profit(self):
        if self.money_outcome == 0:
            return 0
        else:
            return self.money_income - self.money_outcome

    def show_profit_percent(self):
        if self.money_outcome == 0:
            return 0
        else:
            return (self.show_profit()/self.money_income)*100

    def show_average_profit_per_order(self):
        if self.order_number ==0:
            return 0
        else:
            return self.show_profit()/self.order_number



    def show_average_order_income(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_income/self.order_number

    def show_average_order_outcome(self):
        if self.order_number ==0:
            return 0
        else:
            return self.money_outcome/self.order_number










class Table(models.Model):
    STATUS_ =(('a','Διαθέσιμο'),('b','Παραγγελία σε εξέλιξη'),('c','Απενεργοποιημένπ'))
    title = models.CharField(max_length=10, unique=True, )
    status = models.CharField(max_length=1, choices=STATUS_, default='a')

    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name="Τραπέζια"



class RestoOrder(models.Model):
    STATUS_CHOICES =(('a','Σε εξέλιξη'),('b','Αποπληρώθηκε'),('c','Ακύρωση'))
    title = models.CharField(max_length=50,default=timezone.now)
    notes = models.TextField(null=True,blank=True)
    table = models.ForeignKey(Table,verbose_name='Τραπέζι', on_delete=models.CASCADE)
    day_added = models.DateTimeField(default=timezone.now)
    discount = models.IntegerField(default=0, verbose_name='Έκπτωση',)

    value = models.DecimalField(max_digits=6,decimal_places=2,default=0,verbose_name='Αξία Παραγγελίας')
    total_cost  = models.DecimalField(max_digits=6,decimal_places=2,default=0,verbose_name='Συνολικό Κόστος Παραγγελίας')
    paid_value = models.DecimalField(max_digits=6,decimal_places=2,default=0,verbose_name='Αποπληρωμένο Πόσο')
    status = models.CharField(max_length=1,choices=STATUS_CHOICES, default='a')




    year = models.ForeignKey(YearlyIncomeGreg, null=True, blank=True, on_delete=models.CASCADE)
    month =models.ForeignKey(MonthlyIncomeGreG,null=True, blank=True, on_delete=models.CASCADE)
    day = models.ForeignKey(DailyIncomeGreG,null=True,blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name="Παραγγελία Εστιατορίου"
        
        
        
    def remaining_value(self):
        return str(self.value - self.paid_value)

    def __str__(self):
        return self.title

    def order_table_closed(self,dk):
        # gets the order
        order = RestoOrder.objects.get(id= dk)


        #updates the daily ,monthly,yearly incomes and costs
        order.day.money_income += order.paid_value
        order.day.money_outcome +=order.total_cost
        order.day.save()

        order.month.money_income += order.paid_value
        order.month.money_outcome += order.total_cost
        order.month.order_number +=1
        order.month.save()

        order.year.money_income += order.paid_value
        order.year.money_outcome += order.total_cost
        order.year.order_number +=1
        order.year.save()
        #---------------------------------

        #get the order products
        order_items = order.restoorderitem_set.all()
        for ele in order_items:
            # order quantity per item
            quantity = ele.qty
            # updates the Recipes categories cost and income
            ele.title.category.day_cost += ele.title.recipe_cost*ele.qty
            ele.title.category.month_cost += ele.title.recipe_cost*ele.qty
            ele.title.category.yearly_cost += ele.title.recipe_cost*ele.qty
            #ele.title.category.costum_cost_cost += ele.title.recipe_cost

            ele.title.category.day_income += ele.title.recipe_price*ele.qty
            ele.title.category.month_income += ele.title.recipe_price*ele.qty
            ele.title.category.yearly_income += ele.title.recipe_price*ele.qty
            #ele.title.category.costum_income += ele.title.recipe_price
            ele.title.category.save()

            #gets th products for every recipe
            recipe_item = ele.title.recipeitem_set.all()
            #updates the warehouse stock for very product used on Recipes
            for ele in recipe_item:
                qty_kila = ele.product.qty_kilo
                posotita = ele.qty
                ele.product.reserve -= (quantity*posotita)/qty_kila
                ele.product.save()

        order.status='b'
        order.save()






class RestoOrderItem(models.Model):
    title = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    order = models.ForeignKey(RestoOrder, on_delete=models.CASCADE)
    cost =  models.DecimalField(max_digits=6,decimal_places=2,default=0)
    price = models.DecimalField(max_digits=6,decimal_places=2,default=0)
    qty= models.DecimalField(max_digits=3,decimal_places=1,default=1, verbose_name='Ποσότητα')

    class Meta:

esoda_katastimata/templates/pos/lianiki/homepage.html
{% extends 'PoS/homepage.html' %}



{% block center %}
    <div class="ui segments">

        <div style="text-align: center;" class="ui blue inverted header segment">
            Πωλήσεις Λιανικής
        </div>
        <div class="ui horizontal segments">
            <div class="ui blue inverted segment">
                <a href="/PoS/lianiki/new-order/" style="width: 100%; height: 100px;text-align: center" class="ui huge green  button">Πώληση Λιανικής</a>
            </div>
            <div class="ui blue inverted segment">
                <a  style="width: 100%; height: 100px;text-align: center" class="ui huge green  button">Πώληση Χονδρικής</a>
            </div>

        </div>
        <div class="ui blue inverted divider segment"></div>

        <div class="ui blue inverted segment">
                <a href="/PoS/lianiki/create-return/"  style="width: 100%; height: 100px;text-align: center" class="ui huge red  button">Επιστροφές Προιόντων</a>
        </div>
        <div class="ui blue inverted divider segment"></div>
        <div style="text-align: center;" class="ui blue inverted header segment">
            Πωλήσεις Ημέρας , Σύνολο {{ day.money_income }} €
        </div>
        <table class="ui table segment">
            <thead>

            </thead>

        </table>




    </div>




{% endblock %}

esoda_katastimata/templates/pos/lianiki/lianiki_add_product.html
{% extends 'PoS/lianiki/show_categories_lianiki.html' %}


{% block center %}
    <style>
    .ui form{
        text-align: center;
    }
    label[for=id_title],label[for=id_order],label[for=id_cost],label[for=id_color],label[for=id_size]{
        display: none;
    }
    #id_title, #id_order, #id_cost, #id_color, #id_size{
        display: none;
    }
    label[for=id_qty],label[for=id_price]{
        height: 50px;
        text-align: center;
        font-size: 30px;
        color: #0099d4;

    }
    #id_qty,#id_price,#id_paid_value{
        height: 100px;
        text-align: center;
        font-size: 80px;
        margin: 1%;
    }

    </style>

    {% if messages %}
        <div class="ui green message">
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div class="ui segments">
        <div class="ui inverted blue segment">
            <h2 style="text-align: center">{{ product.title }}, Προμηθευτής {{ product.supplier.title }}</h2>
        </div>
        <div class="ui segments">
            <div class="ui segment">
                <a href="/PoS/lianiki/order/{{ order.id }}/" class="ui massive green button"><i class="huge browser icon"></i><br>Επιστροφή</a>
            </div>
            <div class="ui divider segment">Επιλογή Ποσότητας  Τιμή {{ product.price|floatformat:2 }} €</div>
            {% if product.size == 'a' %}
                <div class="ui segment">
                    {% for ele in product_size %}
                        <a class="ui blue button" href="/PoS/lianiki/order/{{ order.id }}/{{ product.id }}/{{ ele.id }}/">
                            {{ ele.color.title }}
                            <br>{{ ele.title }}
                            <br>
                        </a>
                    {% endfor %}
                </div>
            {% elif product.color == 'a' %}
                <div class="ui segment">
                    {% for ele in products_colors %}
                        <a class="ui blue button" href="/PoS/lianiki/order/only_color/{{ order.id }}/{{ product.id }}/{{ ele.id }}/">
                            {{ ele.title }}

                        </a>
                    {% endfor %}
                </div>
            {% else %}
                <div class="ui segment">
                    <div class="ui form">
                        <form class="ui form" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                            {{ form }}
                            <input  style="width: 100%;height: 200px; font-size: 50px;" type="submit" name="submit" class="ui green button segment" value="Προσθήκη"/>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


{% endblock %}


{% block right_side %}
    <div class="ui segments">
        <div style="text-align: center" class="ui inverted red segment">
            Όδηγίες!
        </div>
        <div class="ui segment">
            <h1>ΠΕΙΡΑΖΕΙΣ ΜΟΝΟ την Τιμή εαν θες να κάνεις έκπτωση, και την Ποσότητα ανάλογα την παραγγελία</h1>
        </div>
    </div>



{% endblock %}

esoda_katastimata/templates/pos/lianiki/lianiki_category.html
{% extends 'PoS/lianiki/show_categories_lianiki.html' %}


{% block center %}
    <div style="width: 85%" class="ui segments">
        <div class="ui inverted blue segment">
            <h2 style="text-align: center">{{ categories.title }}</h2>
        </div>
        <div class="ui segments">
            <div class="ui horizontal segments">
                <div class="ui segment">

                <a href="/PoS/lianiki/order/{{ order.id }}" class="ui massive green button"><i class="huge browser icon"></i><br>Επιστροφή</a>

                </div>
                <div class="ui segment">
                <form method="get">
                    <div class="ui search">
                        <div style="width: 100%; text-align: center;" class="ui icon input">
                            <input  class="prompt" name="search_products" type="text" placeholder="Αναζήτηση Προϊόντος..">
                            <i class="search icon"></i>
                        </div>
                        <div class="results"></div>
                    </div>
                </form>
            </div>
            </div>


            <div class="ui divider segment">Ολα τα Προιόντα</div>
            <div class="ui segment">
                {% for ele in products %}

                <a style="width: 30%;height:200px;text-align: center" href="/PoS/lianiki/order/{{ order.id }}/{{ ele.id }}/add/" class="ui huge  button segment">
                    <section style="color: #ff6415">{{ ele.title|truncatechars:20 }}<br>
                    <br>Τιμή: {{ ele.price }} €</section>

                    Κωδικός Barcode:{{ ele.product_id }}
                    </a>
                {% endfor %}

            </div>
        </div>
    </div>


{% endblock %}

esoda_katastimata/templates/pos/lianiki/new_lianiki_order.html
{% extends 'PoS/homepage.html' %}


{% block center %}
     <style>
    .ui form{
        text-align: center;
    }
    label[for=id_day],label[for=id_month],label[for=id_year]{
        display: none;
    }
    #id_day, #id_month, #id_year{
        display: none;
    }
    label[for=id_title],label[for=id_notes]{
        height: 50px;
        text-align: center;
        font-size: 30px;
        color: #0099d4;

    }
    #id_title,#id_notes{
        height: 100px;
        text-align: center;
        font-size: 40px;
        margin: 1%;
    }

    </style>

    <div class="ui segments">
        <div style="text-align: center" class="ui black inverted header segment">
            <h3>Επιβεβαίωση</h3>
        </div>
         <form style="text-align: center;font-size: larger" class="ui form segment" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
            {{ form }}
            <input style="width: 100%;height: 300px; font-size: 50px;" type="submit" name="submit" class="ui huge green button" value="Νέα Παραγγελία"/>
        </form>
    </div>



{% endblock %}


{% block right_side %}
    <div class="ui segments">
        <div style="text-align: center" class="ui inverted red segment">
            Όδηγίες!
        </div>
        <div class="ui segment">
            <p>Το μόνο που αλλάζεις εάν θες είναι ο τίτλος, και οι Σημειώσεις</p>
        </div>
    </div>

{% endblock %}